executable   = Submit1163_2016apv.sh
max_retries  = 1
batch_name   = Comb1163_2016apv
output       = 2016apv_1163.out
error        = 2016apv_1163.err
log          = 2016apv_1163.log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "tomorrow"
RequestCpus  = 2
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 1
