executable   = SubmitSplit1153_2016apv.sh
arguments    = $(ProcID)
max_retries  = 1
batch_name   = SplitScan1153_2016apv
output       = SplitScan2016apv_1153_$(ProcID).out
error        = SplitScan2016apv_1153_$(ProcID).err
log          = SplitScan2016apv_1153_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "nextweek"
RequestCpus  = 2
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 9

