executable   = SubmitSplit2163_2016.sh
arguments    = $(ProcID)
max_retries  = 1
batch_name   = SplitScan2163_2016
output       = SplitScan2016_2163_$(ProcID).out
error        = SplitScan2016_2163_$(ProcID).err
log          = SplitScan2016_2163_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "testmatch"
RequestCpus  = 2
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 9

