executable   = Submit2153_2016apv.sh
max_retries  = 1
batch_name   = Comb2153_2016apv
output       = 2016apv_2153.out
error        = 2016apv_2153.err
log          = 2016apv_2153.log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "tomorrow"
RequestCpus  = 2
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 1
