executable   = SubmitGoFtestCRsOnly.sh
arguments    = $(ProcID)
max_retries  = 0
batch_name   = SubmitGoFtestCRsOnly_$(ProcID)
log          = SubmitGoFtestCRsOnly_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "tomorrow"
RequestCpus  = 1
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 9

