executable   = SubmitSplit2153_2016apv.sh
arguments    = $(ProcID)
max_retries  = 0
batch_name   = SplitScan2153_2016apv
log          = SplitScan2016apv_2153_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "testmatch"
RequestCpus  = 2
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 9

