executable   = SubmitSignalInjectionTest.sh
arguments    = $(ProcID)
max_retries  = 0
batch_name   = SubmitSignalInjectionTest_$(ProcID)
log          = SubmitSignalInjectionTest_$(ProcID).log
universe     = vanilla
Requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "testmatch"
RequestCpus  = 1
stream_error = True
periodic_release =  (NumJobStarts < 10) && ((CurrentTime - EnteredCurrentStatus) > (5*60))
queue 18

